# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `code_ownership` gem.
# Please instead update this file by running `bin/tapioca gem code_ownership`.


# source://code_ownership//lib/code_ownership/version.rb#4
module CodeOwnership
  class << self
    # Generally, you should not ever need to do this, because once your ruby process loads, cached content should not change.
    # Namely, the set of files, packages, and directories which are tracked for ownership should not change.
    # The primary reason this is helpful is for clients of CodeOwnership who want to test their code, and each test context
    # has different ownership and tracked files.
    #
    # source://code_ownership//lib/code_ownership.rb#316
    sig { void }
    def bust_caches!; end

    # Given a backtrace from either `Exception#backtrace` or `caller`, find the
    # first owned file in it, useful for figuring out which file is being blamed.
    #
    # source://code_ownership//lib/code_ownership.rb#297
    sig do
      params(
        backtrace: T.nilable(T::Array[::String]),
        excluded_teams: T::Array[::CodeTeams::Team]
      ).returns(T.nilable([::CodeTeams::Team, ::String]))
    end
    def first_owned_file_for_backtrace(backtrace, excluded_teams: T.unsafe(nil)); end

    # Given a backtrace from either `Exception#backtrace` or `caller`, find the
    # first line that corresponds to a file with assigned ownership
    #
    # source://code_ownership//lib/code_ownership.rb#290
    sig do
      params(
        backtrace: T.nilable(T::Array[::String]),
        excluded_teams: T::Array[::CodeTeams::Team]
      ).returns(T.nilable(::CodeTeams::Team))
    end
    def for_backtrace(backtrace, excluded_teams: T.unsafe(nil)); end

    # source://code_ownership//lib/code_ownership.rb#302
    sig do
      params(
        klass: T.nilable(T.any(T::Class[T.anything], T::Module[T.anything]))
      ).returns(T.nilable(::CodeTeams::Team))
    end
    def for_class(klass); end

    # Returns the owning team for a given file path.
    #
    # @example Find owner for a file using CODEOWNERS
    #   team = CodeOwnership.for_file('app/models/user.rb')
    #   # => #<CodeTeams::Team:0x... @name="platform">
    # @example Find owner without using CODEOWNERS
    #   team = CodeOwnership.for_file('app/models/user.rb', from_codeowners: false)
    #   # => #<CodeTeams::Team:0x... @name="platform">
    # @example Raise if no owner is found
    #   team = CodeOwnership.for_file('unknown_file.rb', allow_raise: true)
    #   # => raises exception if no owner found
    #
    # source://code_ownership//lib/code_ownership.rb#63
    sig do
      params(
        file: ::String,
        from_codeowners: T::Boolean,
        allow_raise: T::Boolean
      ).returns(T.nilable(::CodeTeams::Team))
    end
    def for_file(file, from_codeowners: T.unsafe(nil), allow_raise: T.unsafe(nil)); end

    # Returns detailed ownership information for a given file path.
    #
    # This method provides verbose ownership details including the team name,
    # team configuration file path, and the reasons/sources for ownership assignment.
    # It's particularly useful for debugging ownership assignments and understanding
    # why a file is owned by a specific team.
    #
    # The returned hash contains the following keys when an owner is found:
    # - :team_name [String] - The name of the owning team
    # - :team_config_yml [String] - Path to the team's configuration YAML file
    # - :reasons [Array<String>] - List of reasons/sources explaining why this team owns the file
    #                               (e.g., "CODEOWNERS pattern: /app/models/**", "Package ownership")
    #
    # @example Get verbose ownership details
    #   details = CodeOwnership.for_file_verbose('app/models/user.rb')
    #   # => {
    #   #   team_name: "platform",
    #   #   team_config_yml: "config/teams/platform.yml",
    #   #   reasons: ["Matched pattern '/app/models/**' in CODEOWNERS"]
    #   # }
    # @example Handle unowned files
    #   details = CodeOwnership.for_file_verbose('unowned_file.txt')
    #   # => nil
    # @note This method is primarily used by the CLI tool when the --verbose flag is provided,
    #   allowing users to understand the ownership assignment logic.
    # @note Unlike `for_file`, this method always uses the CODEOWNERS file and other ownership
    #   sources to determine ownership, providing complete context about the ownership decision.
    # @see #for_file for a simpler ownership lookup that returns just the team
    # @see CLI#for_file for the command-line interface that uses this method
    #
    # source://code_ownership//lib/code_ownership.rb#158
    sig { params(file: ::String).returns(T.nilable(T::Hash[::Symbol, ::String])) }
    def for_file_verbose(file); end

    # source://code_ownership//lib/code_ownership.rb#307
    sig { params(package: ::Packs::Pack).returns(T.nilable(::CodeTeams::Team)) }
    def for_package(package); end

    # source://code_ownership//lib/code_ownership.rb#163
    sig { params(team: T.any(::CodeTeams::Team, ::String)).returns(T::Array[::String]) }
    def for_team(team); end

    # Removes the file annotation (e.g., "# @team TeamName") from a file.
    #
    # This method removes the ownership annotation from the first line of a file,
    # which is typically used to declare team ownership at the file level.
    # The annotation can be in the form of:
    # - Ruby comments: # @team TeamName
    # - JavaScript/TypeScript comments: // @team TeamName
    # - YAML comments: -# @team TeamName
    #
    # If the file does not have an annotation or the annotation doesn't match a valid team,
    # this method does nothing.
    #
    # @example Remove annotation from a JavaScript file
    #   # Before: File contains "// @team Frontend\nexport default function() {}"
    #   CodeOwnership.remove_file_annotation!('app/javascript/component.js')
    #   # After: File contains "export default function() {}"
    # @example Remove annotation from a Ruby file
    #   # Before: File contains "# @team Platform\nclass User; end"
    #   CodeOwnership.remove_file_annotation!('app/models/user.rb')
    #   # After: File contains "class User; end"
    # @note This method modifies the file in place.
    # @note Leading newlines after the annotation are also removed to maintain clean formatting.
    #
    # source://code_ownership//lib/code_ownership.rb#267
    sig { params(filename: ::String).void }
    def remove_file_annotation!(filename); end

    # Returns the owning teams for multiple file paths using the CODEOWNERS file.
    #
    # This method efficiently determines ownership for multiple files in a single operation
    # by leveraging the generated CODEOWNERS file. It's more performant than calling
    # `for_file` multiple times when you need to check ownership for many files.
    #
    # @example Get owners for multiple files
    #   files = ['app/models/user.rb', 'app/controllers/users_controller.rb', 'config/routes.rb']
    #   owners = CodeOwnership.teams_for_files_from_codeowners(files)
    #   # => {
    #   #   'app/models/user.rb' => #<CodeTeams::Team:0x... @name="platform">,
    #   #   'app/controllers/users_controller.rb' => #<CodeTeams::Team:0x... @name="platform">,
    #   #   'config/routes.rb' => #<CodeTeams::Team:0x... @name="infrastructure">
    #   # }
    # @example Handle files without owners
    #   files = ['owned_file.rb', 'unowned_file.txt']
    #   owners = CodeOwnership.teams_for_files_from_codeowners(files)
    #   # => {
    #   #   'owned_file.rb' => #<CodeTeams::Team:0x... @name="backend">,
    #   #   'unowned_file.txt' => nil
    #   # }
    # @note This method uses caching internally for performance. The cache is populated
    #   as files are processed and reused for subsequent lookups.
    # @note This method relies on the CODEOWNERS file being up-to-date. Run
    #   `CodeOwnership.validate!` to ensure the CODEOWNERS file is current.
    # @see #for_file for single file ownership lookup
    # @see #validate! for ensuring CODEOWNERS file is up-to-date
    #
    # source://code_ownership//lib/code_ownership.rb#114
    sig do
      params(
        files: T::Array[::String],
        allow_raise: T::Boolean
      ).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)])
    end
    def teams_for_files_from_codeowners(files, allow_raise: T.unsafe(nil)); end

    # Validates code ownership configuration and optionally corrects issues.
    #
    # This method performs comprehensive validation of the code ownership setup, ensuring:
    # 1. Only one ownership mechanism is defined per file (no conflicts between annotations, packages, or globs)
    # 2. All referenced teams are valid (exist in CodeTeams configuration)
    # 3. All files have ownership (unless explicitly listed in unowned_globs)
    # 4. The .github/CODEOWNERS file is up-to-date and properly formatted
    #
    # When autocorrect is enabled, the method will automatically:
    # - Generate or update the CODEOWNERS file based on current ownership rules
    # - Fix any formatting issues in the CODEOWNERS file
    # - Stage the corrected CODEOWNERS file (unless stage_changes is false)
    #
    # @example Basic validation with autocorrection
    #   CodeOwnership.validate!
    #   # Validates all files and auto-corrects/stages CODEOWNERS if needed
    # @example Validate and fix but don't stage changes
    #   CodeOwnership.validate!(autocorrect: true, stage_changes: false)
    #   # Fixes CODEOWNERS but doesn't stage it with git
    # @example Validation without making changes
    #   CodeOwnership.validate!(autocorrect: false)
    #   # Only checks for issues without updating CODEOWNERS
    # @note The validation can be disabled for CODEOWNERS by setting skip_codeowners_validation: true in config/code_ownership.yml
    # @note This method is called by the CLI command: bin/codeownership validate
    # @raise [RuntimeError] Raises an error if validation fails with details about:
    #   - Files with conflicting ownership definitions
    #   - References to non-existent teams
    #   - Files without ownership (not in unowned_globs)
    #   - CODEOWNERS file inconsistencies
    # @see CLI.validate! for the command-line interface
    # @see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners for CODEOWNERS format
    #
    # source://code_ownership//lib/code_ownership.rb#224
    sig { params(autocorrect: T::Boolean, stage_changes: T::Boolean, files: T.nilable(T::Array[::String])).void }
    def validate!(autocorrect: T.unsafe(nil), stage_changes: T.unsafe(nil), files: T.unsafe(nil)); end

    # Returns the version of the code_ownership gem and the codeowners-rs gem.
    #
    # source://code_ownership//lib/code_ownership.rb#33
    sig { returns(T::Array[::String]) }
    def version; end
  end
end

# source://code_ownership//lib/code_ownership/cli.rb#9
class CodeOwnership::Cli
  class << self
    # For now, this just returns team ownership
    # Later, this could also return code ownership errors about that file.
    #
    # source://code_ownership//lib/code_ownership/cli.rb#95
    def for_file(argv); end

    # source://code_ownership//lib/code_ownership/cli.rb#129
    def for_team(argv); end

    # source://code_ownership//lib/code_ownership/cli.rb#12
    def run!(argv); end

    # source://code_ownership//lib/code_ownership/cli.rb#37
    def validate!(argv); end

    # source://code_ownership//lib/code_ownership/cli.rb#89
    def version; end
  end
end

# source://code_ownership//lib/code_ownership/cli.rb#10
CodeOwnership::Cli::EXECUTABLE = T.let(T.unsafe(nil), String)

# source://code_ownership//lib/code_ownership.rb#29
CodeOwnership::GlobsToOwningTeamMap = T.type_alias { T::Hash[::String, ::CodeTeams::Team] }

# source://code_ownership//lib/code_ownership/private/file_path_finder.rb#5
module CodeOwnership::Private; end

# source://code_ownership//lib/code_ownership/private/file_path_finder.rb#6
module CodeOwnership::Private::FilePathFinder
  class << self
    # source://code_ownership//lib/code_ownership/private/file_path_finder.rb#22
    sig { params(backtrace: T.nilable(T::Array[::String])).returns(T::Enumerable[::String]) }
    def from_backtrace(backtrace); end

    # Returns a string version of the relative path to a Rails constant,
    # or nil if it can't find anything
    #
    # source://code_ownership//lib/code_ownership/private/file_path_finder.rb#12
    sig { params(klass: T.nilable(T.any(T::Class[T.anything], T::Module[T.anything]))).returns(T.nilable(::String)) }
    def path_from_klass(klass); end
  end
end

# source://code_ownership//lib/code_ownership/private/file_path_team_cache.rb#6
module CodeOwnership::Private::FilePathTeamCache
  class << self
    # source://code_ownership//lib/code_ownership/private/file_path_team_cache.rb#25
    sig { void }
    def bust_cache!; end

    # source://code_ownership//lib/code_ownership/private/file_path_team_cache.rb#30
    sig { returns(T::Hash[::String, T.nilable(::CodeTeams::Team)]) }
    def cache; end

    # source://code_ownership//lib/code_ownership/private/file_path_team_cache.rb#20
    sig { params(file_path: ::String).returns(T::Boolean) }
    def cached?(file_path); end

    # source://code_ownership//lib/code_ownership/private/file_path_team_cache.rb#10
    sig { params(file_path: ::String).returns(T.nilable(::CodeTeams::Team)) }
    def get(file_path); end

    # source://code_ownership//lib/code_ownership/private/file_path_team_cache.rb#15
    sig { params(file_path: ::String, team: T.nilable(::CodeTeams::Team)).void }
    def set(file_path, team); end
  end
end

# source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#6
class CodeOwnership::Private::ForFileOutputBuilder
  # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#12
  sig { params(file_path: ::String, json: T::Boolean, verbose: T::Boolean).void }
  def initialize(file_path:, json:, verbose:); end

  # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#32
  sig { returns(::String) }
  def build; end

  private

  # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#78
  sig { params(reasons: T::Array[::String]).returns(::String) }
  def build_description_message(reasons); end

  # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#69
  sig { params(result_hash: T::Hash[::Symbol, T.untyped]).returns(::String) }
  def build_message_for(result_hash); end

  # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#55
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def build_terse; end

  # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#43
  sig { returns(T::Hash[::Symbol, T.untyped]) }
  def build_verbose; end

  class << self
    # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#19
    sig { params(file_path: ::String, json: T::Boolean, verbose: T::Boolean).returns(::String) }
    def build(file_path:, json:, verbose:); end

    private

    # source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#9
    def new(*_arg0); end
  end
end

# source://code_ownership//lib/code_ownership/private/for_file_output_builder.rb#23
CodeOwnership::Private::ForFileOutputBuilder::UNOWNED_OUTPUT = T.let(T.unsafe(nil), Hash)

# source://code_ownership//lib/code_ownership/private/team_finder.rb#6
module CodeOwnership::Private::TeamFinder
  class << self
    # source://code_ownership//lib/code_ownership/private/team_finder.rb#76
    sig do
      params(
        backtrace: T.nilable(T::Array[::String]),
        excluded_teams: T::Array[::CodeTeams::Team]
      ).returns(T.nilable([::CodeTeams::Team, ::String]))
    end
    def first_owned_file_for_backtrace(backtrace, excluded_teams: T.unsafe(nil)); end

    # source://code_ownership//lib/code_ownership/private/team_finder.rb#71
    sig do
      params(
        backtrace: T.nilable(T::Array[::String]),
        excluded_teams: T::Array[::CodeTeams::Team]
      ).returns(T.nilable(::CodeTeams::Team))
    end
    def for_backtrace(backtrace, excluded_teams: T.unsafe(nil)); end

    # source://code_ownership//lib/code_ownership/private/team_finder.rb#55
    sig do
      params(
        klass: T.nilable(T.any(T::Class[T.anything], T::Module[T.anything]))
      ).returns(T.nilable(::CodeTeams::Team))
    end
    def for_class(klass); end

    # source://code_ownership//lib/code_ownership/private/team_finder.rb#10
    sig { params(file_path: ::String, allow_raise: T::Boolean).returns(T.nilable(::CodeTeams::Team)) }
    def for_file(file_path, allow_raise: T.unsafe(nil)); end

    # source://code_ownership//lib/code_ownership/private/team_finder.rb#63
    sig { params(package: ::Packs::Pack).returns(T.nilable(::CodeTeams::Team)) }
    def for_package(package); end

    # source://code_ownership//lib/code_ownership/private/team_finder.rb#28
    sig do
      params(
        files: T::Array[::String],
        allow_raise: T::Boolean
      ).returns(T::Hash[::String, T.nilable(::CodeTeams::Team)])
    end
    def teams_for_files(files, allow_raise: T.unsafe(nil)); end

    private

    # source://code_ownership//lib/code_ownership/private/team_finder.rb#88
    sig { params(team_name: ::String, allow_raise: T::Boolean).returns(T.nilable(::CodeTeams::Team)) }
    def find_team!(team_name, allow_raise: T.unsafe(nil)); end
  end
end

# source://code_ownership//lib/code_ownership/version.rb#5
CodeOwnership::VERSION = T.let(T.unsafe(nil), String)
