# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `code_teams` gem.
# Please instead update this file by running `bin/tapioca gem code_teams`.


# source://code_teams//lib/code_teams/plugin.rb#3
module CodeTeams
  class << self
    # source://code_teams//lib/code_teams.rb#22
    sig { returns(T::Array[::CodeTeams::Team]) }
    def all; end

    # Generally, you should not ever need to do this, because once your ruby process loads, cached content should not change.
    # Namely, the YML files that are the source of truth for teams should not change, so we should not need to look at the YMLs again to verify.
    # The primary reason this is helpful is for clients of CodeTeams who want to test their code, and each test context has different set of teams
    #
    # source://code_teams//lib/code_teams.rb#67
    sig { void }
    def bust_caches!; end

    # source://code_teams//lib/code_teams.rb#27
    sig { params(name: ::String).returns(T.nilable(::CodeTeams::Team)) }
    def find(name); end

    # source://code_teams//lib/code_teams.rb#33
    sig { params(name: ::String).returns(::CodeTeams::Team) }
    def find!(name); end

    # source://code_teams//lib/code_teams.rb#38
    sig { params(dir: ::String).returns(T::Array[::CodeTeams::Team]) }
    def for_directory(dir); end

    # source://code_teams//lib/code_teams.rb#59
    sig { params(string: ::String).returns(::String) }
    def tag_value_for(string); end

    # source://code_teams//lib/code_teams.rb#52
    sig { params(teams: T::Array[::CodeTeams::Team]).returns(T::Array[::String]) }
    def validation_errors(teams); end
  end
end

# source://code_teams//lib/code_teams.rb#15
class CodeTeams::IncorrectPublicApiUsageError < ::StandardError; end

# Plugins allow a client to add validation on custom keys in the team YML.
# For now, only a single plugin is allowed to manage validation on a top-level key.
# In the future we can think of allowing plugins to be gracefully merged with each other.
#
# @abstract It cannot be directly instantiated. Subclasses must implement the `abstract` methods below.
#
# source://code_teams//lib/code_teams/plugin.rb#7
class CodeTeams::Plugin
  abstract!

  # source://code_teams//lib/code_teams/plugin.rb#16
  sig { params(team: ::CodeTeams::Team).void }
  def initialize(team); end

  class << self
    # source://code_teams//lib/code_teams/plugin.rb#37
    sig { returns(T::Array[T.class_of(CodeTeams::Plugin)]) }
    def all_plugins; end

    # source://code_teams//lib/code_teams/plugin.rb#78
    sig { void }
    def bust_caches!; end

    # source://code_teams//lib/code_teams/plugin.rb#83
    sig { void }
    def clear_team_registry!; end

    # source://code_teams//lib/code_teams/plugin.rb#21
    sig { params(key: ::String).returns(::String) }
    def data_accessor_name(key = T.unsafe(nil)); end

    # source://code_teams//lib/code_teams/plugin.rb#26
    sig { returns(::String) }
    def default_data_accessor_name; end

    # source://code_teams//lib/code_teams/plugin.rb#49
    sig { params(team: ::CodeTeams::Team).returns(T.attached_class) }
    def for(team); end

    # source://code_teams//lib/code_teams/plugin.rb#32
    sig { params(base: T.class_of(CodeTeams::Plugin)).void }
    def inherited(base); end

    # source://code_teams//lib/code_teams/plugin.rb#54
    sig { params(team: ::CodeTeams::Team, key: ::String).returns(::String) }
    def missing_key_error_message(team, key); end

    # source://code_teams//lib/code_teams/plugin.rb#44
    sig { params(teams: T::Array[::CodeTeams::Team]).returns(T::Array[::String]) }
    def validation_errors(teams); end

    private

    # source://code_teams//lib/code_teams/plugin.rb#66
    sig { params(team: ::CodeTeams::Team).returns(T.attached_class) }
    def register_team(team); end

    # source://code_teams//lib/code_teams/plugin.rb#59
    sig { returns(T::Hash[T.nilable(::String), T::Hash[T.class_of(CodeTeams::Plugin), ::CodeTeams::Plugin]]) }
    def registry; end
  end
end

# source://code_teams//lib/code_teams/plugins/identity.rb#4
module CodeTeams::Plugins; end

# source://code_teams//lib/code_teams/plugins/identity.rb#5
class CodeTeams::Plugins::Identity < ::CodeTeams::Plugin
  # source://code_teams//lib/code_teams/plugins/identity.rb#12
  sig { returns(::CodeTeams::Plugins::Identity::IdentityStruct) }
  def identity; end

  class << self
    # source://code_teams//lib/code_teams/plugins/identity.rb#19
    sig { override.params(teams: T::Array[::CodeTeams::Team]).returns(T::Array[::String]) }
    def validation_errors(teams); end
  end
end

# source://code_teams//lib/code_teams/plugins/identity.rb#9
class CodeTeams::Plugins::Identity::IdentityStruct < ::Struct
  # Returns the value of attribute name
  #
  # @return [Object] the current value of name
  #
  # source://code_teams//lib/code_teams/plugins/identity.rb#9
  def name; end

  # Sets the attribute name
  #
  # @param value [Object] the value to set the attribute name to.
  # @return [Object] the newly set value
  #
  # source://code_teams//lib/code_teams/plugins/identity.rb#9
  def name=(_); end

  class << self
    # source://code_teams//lib/code_teams/plugins/identity.rb#9
    def [](*_arg0); end

    # source://code_teams//lib/code_teams/plugins/identity.rb#9
    def inspect; end

    # source://code_teams//lib/code_teams/plugins/identity.rb#9
    def keyword_init?; end

    # source://code_teams//lib/code_teams/plugins/identity.rb#9
    def members; end

    # source://code_teams//lib/code_teams/plugins/identity.rb#9
    def new(*_arg0); end
  end
end

# source://code_teams//lib/code_teams.rb#74
class CodeTeams::Team
  # source://code_teams//lib/code_teams.rb#118
  sig { params(config_yml: T.nilable(::String), raw_hash: T::Hash[::String, T.untyped]).void }
  def initialize(config_yml:, raw_hash:); end

  # source://code_teams//lib/code_teams.rb#134
  sig { params(other: ::Object).returns(T::Boolean) }
  def ==(other); end

  # source://code_teams//lib/code_teams.rb#110
  sig { returns(T.nilable(::String)) }
  def config_yml; end

  # @param other [Object]
  # @return [Boolean]
  #
  # source://code_teams//lib/code_teams.rb#142
  def eql?(*args, **_arg1, &blk); end

  # source://code_teams//lib/code_teams.rb#145
  sig { returns(::Integer) }
  def hash; end

  # source://code_teams//lib/code_teams.rb#124
  sig { returns(::String) }
  def name; end

  # source://code_teams//lib/code_teams.rb#107
  sig { returns(T::Hash[::String, T.untyped]) }
  def raw_hash; end

  # source://code_teams//lib/code_teams.rb#129
  sig { returns(::String) }
  def to_tag; end

  class << self
    # source://code_teams//lib/code_teams.rb#88
    sig { params(raw_hash: T::Hash[::String, T.untyped]).returns(::CodeTeams::Team) }
    def from_hash(raw_hash); end

    # source://code_teams//lib/code_teams.rb#78
    sig { params(config_yml: ::String).returns(::CodeTeams::Team) }
    def from_yml(config_yml); end

    # source://code_teams//lib/code_teams.rb#96
    sig { void }
    def register_plugins; end
  end
end

# source://code_teams//lib/code_teams.rb#16
class CodeTeams::TeamNotFoundError < ::StandardError; end

# source://code_teams//lib/code_teams.rb#18
CodeTeams::UNKNOWN_TEAM_STRING = T.let(T.unsafe(nil), String)

# source://code_teams//lib/code_teams/utils.rb#6
module CodeTeams::Utils
  private

  # Recursively converts symbol keys to strings. Top-level input should be a Hash.
  #
  # source://code_teams//lib/code_teams/utils.rb#27
  sig { params(value: T.untyped).returns(T.untyped) }
  def deep_stringify_keys(value); end

  # source://code_teams//lib/code_teams/utils.rb#21
  sig { params(string: ::String).returns(::String) }
  def demodulize(string); end

  # source://code_teams//lib/code_teams/utils.rb#12
  sig { params(string: ::String).returns(::String) }
  def underscore(string); end

  class << self
    # Recursively converts symbol keys to strings. Top-level input should be a Hash.
    #
    # @param value [T.untyped]
    # @return [T.untyped]
    #
    # source://code_teams//lib/code_teams/utils.rb#27
    def deep_stringify_keys(value); end

    # @param string [String]
    # @return [String]
    #
    # source://code_teams//lib/code_teams/utils.rb#21
    def demodulize(string); end

    # @param string [String]
    # @return [String]
    #
    # source://code_teams//lib/code_teams/utils.rb#12
    def underscore(string); end
  end
end
