# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `lint_roller` gem.
# Please instead update this file by running `bin/tapioca gem lint_roller`.


# source://lint_roller//lib/lint_roller/context.rb#1
module LintRoller; end

# source://lint_roller//lib/lint_roller/context.rb#2
class LintRoller::Context < ::Struct
  # Returns the value of attribute engine
  #
  # @return [Object] the current value of engine
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine; end

  # Sets the attribute engine
  #
  # @param value [Object] the value to set the attribute engine to.
  # @return [Object] the newly set value
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine=(_); end

  # Returns the value of attribute engine_version
  #
  # @return [Object] the current value of engine_version
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine_version; end

  # Sets the attribute engine_version
  #
  # @param value [Object] the value to set the attribute engine_version to.
  # @return [Object] the newly set value
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine_version=(_); end

  # Returns the value of attribute rule_format
  #
  # @return [Object] the current value of rule_format
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def rule_format; end

  # Sets the attribute rule_format
  #
  # @param value [Object] the value to set the attribute rule_format to.
  # @return [Object] the newly set value
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def rule_format=(_); end

  # Returns the value of attribute runner
  #
  # @return [Object] the current value of runner
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner; end

  # Sets the attribute runner
  #
  # @param value [Object] the value to set the attribute runner to.
  # @return [Object] the newly set value
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner=(_); end

  # Returns the value of attribute runner_version
  #
  # @return [Object] the current value of runner_version
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner_version; end

  # Sets the attribute runner_version
  #
  # @param value [Object] the value to set the attribute runner_version to.
  # @return [Object] the newly set value
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner_version=(_); end

  # Returns the value of attribute target_ruby_version
  #
  # @return [Object] the current value of target_ruby_version
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def target_ruby_version; end

  # Sets the attribute target_ruby_version
  #
  # @param value [Object] the value to set the attribute target_ruby_version to.
  # @return [Object] the newly set value
  #
  # source://lint_roller//lib/lint_roller/context.rb#2
  def target_ruby_version=(_); end

  class << self
    # source://lint_roller//lib/lint_roller/context.rb#2
    def [](*_arg0); end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def inspect; end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def keyword_init?; end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def members; end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def new(*_arg0); end
  end
end
