# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Rake::DSL; end
module ::Rake::TaskLib; end
module T::InterfaceWrapper::Helpers; end
module T::Private::Abstract::Hooks; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
module T::Private::MixesInClassMethods; end
