# typed: strict

require 'bundler/inline'

# Send is to ward off Sorbet which can't type this method invocation
send(:gemfile) do
  send(:source, 'https://rubygems.org')
  gem 'packs', path: '../'
end

all_docs = []
Packs::CLI.all_commands.each do |_command_name, command|
  all_docs << <<~DOCUMENTATION
    ## #{command.description}
    `bin/packs #{command.usage}`

  DOCUMENTATION

  if command.long_description
    all_docs << command.long_description
    all_docs << "\n"
  end
end

new_autogenerated_content = <<~MARKDOWN.chomp
  ## CLI Documentation
  #{all_docs.join}
  ## Releasing
MARKDOWN

readme = Pathname.new('README.md')
new_content = readme.read.gsub(/## CLI Documentation.*?## Releasing/m, new_autogenerated_content)

if ENV['OVERWRITE']
  readme.write(new_content)
elsif readme.read == new_content
  exit 0
else
  puts 'README.md is out of date. Use OVERWRITE=1 ruby docs/verify_docs.rb'
  exit 1
end
