name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          # See comment comes from https://github.com/ruby/setup-ruby#matrix-of-ruby-versions
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          - '3.0'
          - 3.1
          - head
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "RSpec tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: bundle exec rspec
  static_type_check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: Set up Ruby
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          bundler-cache: true
          ruby-version: head
      - name: Run static type checks
        run: bundle exec srb tc
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: Set up Ruby
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          bundler-cache: true
          ruby-version: head
      - name: Run style checks
        run: bundle exec rubocop
