---
name: Automatically create a new release on tagged main commits

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
